version: '3'
services:
  api:
    image: node:12.18.3
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION=mongodb://scores-admin:scores-pass@db:27017
      - DB_NAME=scores
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on: 
      - db
  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=scores-admin
      - MONGO_INITDB_DATABASE=scores
      - MONGO_INITDB_ROOT_PASSWORD=scores-pass
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
volumes:
  dbdata: